### ISSUE TITLE
Setup your markdown snippets

### ISSUE THREAD

**Issue by SingularisArt** [pilgrimlyieu/Snippets#2]
I'm intrigued by your snippets setup.
How would I set up the markdown snippets?
I just cloned your repo, moved your markdown folder to my snippets location, but when I start typing, I get the following error:

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: Vim(return):Error invoking 'python_execute' on channel 4 (python3-script-host):                                                       
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 679, in _snips
    source.ensure(filetypes)
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 32, in ensure
    self._load_snippets_for(ft)
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 54, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 65, in _parse_snippets
    for event, data in self._parse_snippet_file(file_data, filename):
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/source/file/ulti_snips.py", line 221, in _parse_snippet_file
    for event, data in _parse_snippets_file(filedata, filename):
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/source/file/ulti_snips.py", line 173, in _parse_snippets_file
    snippet = _handle_snippet_or_global(
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/source/file/ulti_snips.py", line 139, in _handle_snippet_or_global
    definition = UltiSnipsSnippetDefinition(
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/definition/base.py", line 114, in __init__
    self.matches(self._trigger)
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/definition/base.py", line 334, in matches
    self._context = self._context_match(visual_content, before)
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/definition/base.py", line 158, in _context_match
    return self._eval_code("snip.context = " + self._context_code, locals).context
  File "/home/hashem/.local/share/nvim/site/pack/packer/start/UltiSnips/pythonx/UltiSnips/snippet/definition/base.py", line 184, in _eval_code
    exec(code, {"snip": snip, "match": self._last_re})
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'markdown_scopes'
stack traceback:
        [C]: in function 'load_snippets'
        ...art/cmp-nvim-ultisnips/lua/cmp_nvim_ultisnips/source.lua:27: in function 'complete'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:296: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:288: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:170: in function 'callback'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:220: in function 'autoindent'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:162: in function 'on_change'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:301: in function 'callback'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
```

**Comment by pilgrimlyieu** [comment]
Thanks for your attention!

> ```
> ModuleNotFoundError: No module named 'markdown_scopes'
> ```

You have to equip python modules in this [repo](https://github.com/pilgrimlyieu/Snippets-Dependencies). More configures are displayed in this [repo](https://github.com/pilgrimlyieu/vimrc).

**Comment by SingularisArt** [comment]
Great! Where did you learn all of this advanced snippet stuff?

**Comment by pilgrimlyieu** [comment]
> Where did you learn all of this advanced snippet stuff?

I think most of information could be found in [documentation](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt), which is detailed. I strongly recommend you to read for more times.

I used to use [HSnips](https://github.com/draivin/hsnips), a similar snippet plugin in VSCode, and studied to learn how to write snippets. However, it is not well maintained and has some bugs that I can't tolerate, so I turn Vim UltiSnips.

**Comment by SingularisArt** [comment]
Thanks! Could you give me some tips on how I could improve the latex snippets that I added in the pull request?

**Comment by SingularisArt** [comment]
Thanks for the information.
By the way, I'm going to use a ton of your snippets and put them in my own configuration.
Do you want me to give you credit in the README?

**Comment by pilgrimlyieu** [comment]
> Do you want me to give you credit in the README?

My pleasure!

**Comment by pilgrimlyieu** [comment]
By the way, 89dbba3 has disabled specific snippets via change snippet name from `snippetname.snippets` to `.snippetname.snippets`. If you need try some of them, you could rechange them.

**Comment by SingularisArt** [comment]
I was wondering why the chemistry files started with a .
Thanks!

**Comment by pilgrimlyieu** [comment]
> I was wondering why the chemistry files started with a .

This could be found

> By the way, https://github.com/pilgrimlyieu/Snippets/commit/89dbba3b6c15e95c16d9eeef5546551aaa7cf08e has disabled specific snippets via change snippet name from snippetname.snippets to .snippetname.snippets. If you need try some of them, you could rechange them.

Beisdes, here are some related macros for Chemistry snippets.

```json
"\\pe": "\\kern-0.023em\\boxed{\\uparrow\\downarrow}\\kern-0.023em",
"\\npe": "\\kern-0.023em\\boxed{\\uparrow\\uparrow}\\kern-0.023em",
"\\nnpe": "\\kern-0.023em\\boxed{\\downarrow\\downarrow}\\kern-0.023em",
"\\se": "\\kern-0.023em\\boxed{\\kern0.25em\\uparrow\\kern0.25em}\\kern-0.023em",
"\\nse": "\\kern-0.023em\\boxed{\\kern0.25em\\downarrow\\kern0.25em}\\kern-0.023em",
"\\oe": "\\kern-0.023em\\boxed{\\kern0.25em\\phantom\\uparrow\\kern0.25em}\\kern-0.023em",
```

**Comment by SingularisArt** [comment]
Quick question. How do you take notes in markdown? How do you create environments, theorems, etc?

**Comment by pilgrimlyieu** [comment]
> How do you take notes in markdown?

Maybe you mean why? I don't think there are many ways to use markdown. If so, I take notes in markdown and turn them into [Anki](https://apps.ankiweb.net/) cards to memorize.

If you mean what's my markdown config. You can find it in my [vimrc](https://github.com/pilgrimlyieu/vimrc/blob/main/_vimrc).

<details><summary>related config</summary>

```vimrc
autocmd FileType tex,markdown,gitcommit setlocal spell spelllang=en_us,cjk
autocmd FileType tex,markdown,gitcommit inoremap <C-m> <C-g>u<Esc>[s1z=`]a<C-g>u

call plug#begin("~/vimfiles/plugged")
Plug 'lervag/vimtex', { 'for': ['tex', 'markdown', 'vim-plug']}
Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown', { 'for': 'markdown'}
Plug 'ferrine/md-img-paste.vim', { 'for': 'markdown'}
call plug#end()

autocmd FileType markdown inoremap <silent><C-w> <C-o>:CocCommand markdown-preview-enhanced.openPreview<Cr>
autocmd FileType markdown nnoremap <silent><C-w> :CocCommand markdown-preview-enhanced.openPreview<Cr>

function! MarkdownTable()
  silent TableFormat
  silent set nowrap
endfunction

let g:vim_markdown_conceal = 1
let g:vim_markdown_math = 1
let g:vim_markdown_conceal_code_blocks = 0
let g:vim_markdown_strikethrough = 1

autocmd FileType markdown nmap <buffer><silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>
let g:mdip_imgdir = 'images'
let g:mdip_imgname = ''
```

</details>

>  How do you create environments, theorems, etc?

Environments could be found in [`markdown/math_environments.snippets`](https://github.com/pilgrimlyieu/Snippets/blob/master/markdown/math_environments.snippets). I seldom use theorems (Because I'm still a high school student) so I didn't add it. You can custom one if you need according to the documentation.
